name: xeus-r-wasm-host
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nlohmann_json
  - xeus-lite
  - xeus >=3.0.5,<4.0
  - xtl >=0.7,<0.8
