name: xeus-r
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  - cxx-compiler
  # Host dependencies
  - xeus >=3.0.5,<3.1.0
  - xeus-zmq >=1.1.0,<2.0
  - nlohmann_json
  - cppzmq
  - xtl
  - r-base >=4
  # Run dependencies
  - r-rlang
  - r-evaluate
  - r-jsonlite
  - r-glue
  - r-cli
  - r-repr
  - r-IRdisplay
  # Test dependencies
  - pytest
  - jupyter_kernel_test >=0.4.3
  - nbval
  - pytest-rerunfailures
  - r-ggplot2
