name: xeus-r-wasm-host
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  # Host dependencies
  - emscripten-abi==3.1.45
  - nlohmann_json
  - xeus-lite
  - xeus
  - pcre2>=10.43
  - zlib>=1.2.13
  - libflang                  # for FortranRuntime
  - xz                        # for lzma
  - bzip2
  - libiconv
  - r-base >=4.4.1
  # Run dependencies
  - r-rlang
  - r-evaluate
  - r-jsonlite
  - r-glue
  - r-cli >=3.6.3
  - r-repr
  - r-IRdisplay
  # Test dependencies
  - r-htmltools
  - r-ggplot2
  - r-munsell >=0.5.1
  - r-colorspace

